[target.x86_64-unknown-linux-musl]
image = "cross-rs-x86_64-unknown-linux-musl:latest"

[target.x86_64-unknown-linux-gnu]
image = "cross-rs-x86_64-unknown-linux-gnu:latest"

[target.aarch64-unknown-linux-gnu]
image = "cross-rs-aarch64-unknown-linux-gnu:latest"
