edition = "2021"

max_width = 80
use_small_heuristics = "max"

# Nightly features
unstable_features = true
version = "Two"

group_imports = "StdExternalCrate"
imports_granularity = "Module"

newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

wrap_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_strings = true

error_on_line_overflow = true
error_on_unformatted = false
