[package]
name = "crible-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
croaring = "0.6.1"
nom = "7.1.1"
rayon = "1.5.3"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0.86"
thiserror = "1.0.37"

[dev-dependencies]
rstest = "0.15.0"
