[package]
name = "crible-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
croaring = "0.5.1"
futures = "0.3.21"
nom = "7.1.1"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
thiserror = "1.0.30"

[dev-dependencies]
criterion = "0.3.5"
rstest = "0.12.0"
