WHITESPACE = _{ " " }

or = { "OR" }
and = { "AND" }
not = { "NOT" }

parens_open = _{"("}
parens_close = _{")"}

token = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_" | "-")* }
primary = { token | (parens_open ~ or_term ~ parens_close) }
factor = { (not ~ factor) | primary }
and_term = { (factor ~ and ~ and_term) | factor }
or_term = { (and_term ~ or ~ or_term) | and_term }

query = { SOI ~ or_term ~ EOI }